from Node import Node


class Config:

    def make_chromosome(self):
        west_azerbaijan = Node(0)
        east_azerbaijan = Node(1)
        ardabil = Node(2)
        kurdistan = Node(3)
        zanjan = Node(4)
        gilan = Node(5)
        kermanshah = Node(6)
        hamedan = Node(7)
        qazvin = Node(8)
        alborz = Node(9)
        mazandaran = Node(10)
        ilam = Node(11)
        lorestan = Node(12)
        markazi = Node(13)
        qom = Node(14)
        tehran = Node(15)
        golestan = Node(16)
        khuzestan = Node(17)
        chaharmahal_va_bakhtiari = Node(18)
        isfahan = Node(19)
        semnan = Node(20)
        north_khorasan = Node(21)
        kohgiluyeh_va_Boyer_Ahmad = Node(22)
        bushehr = Node(23)
        fars = Node(24)
        yazd = Node(25)
        south_khorasan = Node(26)
        razavi_khorasan = Node(27)
        hormozgan = Node(28)
        kerman = Node(29)
        sistan_va_baluchestan = Node(30)

        west_azerbaijan.add_edge([east_azerbaijan, kurdistan, zanjan])
        east_azerbaijan.add_edge([ardabil, zanjan])
        ardabil.add_edge([zanjan, gilan])
        kurdistan.add_edge([zanjan, kermanshah, hamedan])
        zanjan.add_edge([gilan, hamedan, qazvin])
        gilan.add_edge([qazvin, mazandaran])
        kermanshah.add_edge([hamedan, ilam, lorestan])
        hamedan.add_edge([qazvin, lorestan, markazi])
        qazvin.add_edge([alborz, mazandaran, markazi])
        alborz.add_edge([markazi, mazandaran, tehran])
        mazandaran.add_edge([tehran, golestan, semnan])
        ilam.add_edge([lorestan, khuzestan])
        lorestan.add_edge([markazi, khuzestan, chaharmahal_va_bakhtiari, isfahan])
        markazi.add_edge([qom, tehran, isfahan])
        qom.add_edge([tehran, isfahan, semnan])
        tehran.add_edge([semnan, markazi])
        golestan.add_edge([semnan, north_khorasan])
        khuzestan.add_edge([chaharmahal_va_bakhtiari, kohgiluyeh_va_Boyer_Ahmad, bushehr])
        chaharmahal_va_bakhtiari.add_edge([isfahan, kohgiluyeh_va_Boyer_Ahmad])
        isfahan.add_edge([semnan, kohgiluyeh_va_Boyer_Ahmad, fars, yazd, south_khorasan])
        semnan.add_edge([north_khorasan, south_khorasan, razavi_khorasan])
        north_khorasan.add_edge([razavi_khorasan])
        kohgiluyeh_va_Boyer_Ahmad.add_edge([bushehr, fars])
        bushehr.add_edge([fars, hormozgan])
        fars.add_edge([yazd, hormozgan, kerman])
        yazd.add_edge([south_khorasan, kerman])
        south_khorasan.add_edge([razavi_khorasan, kerman, sistan_va_baluchestan])
        razavi_khorasan.add_edge([south_khorasan])
        hormozgan.add_edge([kerman, sistan_va_baluchestan])
        kerman.add_edge([sistan_va_baluchestan])
        sistan_va_baluchestan.add_edge([south_khorasan])

        return [west_azerbaijan, east_azerbaijan, ardabil, kurdistan, zanjan, gilan, kermanshah,
                hamedan, qazvin, alborz, mazandaran, ilam, lorestan, markazi, qom, tehran, golestan,
                khuzestan, chaharmahal_va_bakhtiari, isfahan, semnan, north_khorasan, kohgiluyeh_va_Boyer_Ahmad,
                bushehr, fars, yazd, south_khorasan, razavi_khorasan, hormozgan, kerman, sistan_va_baluchestan]